using CleanBase.Generator.Application.Abstractions;
using CleanBase.Generator.Domain.Entities;

namespace CleanBase.Generator.Infrastructure.Generation;

public sealed class FileSystemTemplateRenderer : ITemplateRenderer
{
    public async Task<IReadOnlyCollection<string>> BuildPreviewPathsAsync(ProjectConfiguration configuration, CancellationToken cancellationToken)
    {
        var paths = new List<string>
        {
            $"{configuration.SolutionName}/src/backend/{configuration.ProjectName}.Api",
            $"{configuration.SolutionName}/src/backend/{configuration.ProjectName}.Application",
            $"{configuration.SolutionName}/src/backend/{configuration.ProjectName}.Domain",
            $"{configuration.SolutionName}/src/backend/{configuration.ProjectName}.Infrastructure",
            $"{configuration.SolutionName}/src/frontend/{configuration.ProjectName}.web"
        };

        if (configuration.IncludeUnitTests)
        {
            paths.Add($"{configuration.SolutionName}/tests/{configuration.ProjectName}.UnitTests");
        }

        paths.AddRange(configuration.SampleModules.Select(m => $"{configuration.SolutionName}/src/backend/modules/{m}"));
        return await Task.FromResult(paths);
    }

    public async Task RenderAsync(ProjectConfiguration configuration, string destinationPath, CancellationToken cancellationToken)
    {
        var root = Path.Combine(destinationPath, configuration.SolutionName);
        Directory.CreateDirectory(root);

        var preview = await BuildPreviewPathsAsync(configuration, cancellationToken);
        foreach (var relativePath in preview)
        {
            Directory.CreateDirectory(Path.Combine(destinationPath, relativePath));
        }

        var readmePath = Path.Combine(root, "README.md");
        var readme = $"# {configuration.SolutionName}\n\nGenerated by CleanBase Generator on {DateTime.UtcNow:O}.\n";
        await File.WriteAllTextAsync(readmePath, readme, cancellationToken);
    }
}
